### ISSUE TITLE
vite antd-vue 报错

### ISSUE THREAD

**Issue by transtone** [GitOfZGT/vite-plugin-theme-preprocessor#17]
```shell
yarn run v1.22.17
$ vite
error when starting dev server:
Error: defaultPrimaryColor can not found.
    at createSetCustomThemeFile (D:\code\hnrr\FE\pc-grid\node_modules\@zougt\some-loader-utils\dist\arbitraryMode\index.js:170:11)
    at D:\code\hnrr\FE\pc-grid\node_modules\@zougt\vite-plugin-theme-preprocessor\dist\common\createSetCustomTheme.js:26:60
    at async Promise.all (index 1)
    at async resolveConfig (D:\code\hnrr\FE\pc-grid\node_modules\vite\dist\node\chunks\dep-e0fe87f8.js:68353:5)
    at async createServer (D:\code\hnrr\FE\pc-grid\node_modules\vite\dist\node\chunks\dep-e0fe87f8.js:66702:20)
    at async CAC.<anonymous> (D:\code\hnrr\FE\pc-grid\node_modules\vite\dist\node\cli.js:687:24)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

 "@zougt/vite-plugin-theme-preprocessor": "^1.4.0-beta.3"

**Comment by GitOfZGT** [comment]
ok，fixed in @zougt/vite-plugin-theme-preprocessor v1.4.0-beta.4

**Comment by GitOfZGT** [comment]
加了新功能，忽略了原来的一个地方，修复咯

**Comment by transtone** [comment]
> ok，fixed in @zougt/vite-plugin-theme-preprocessor v1.4.0-beta

这个版本linux下编译可以，可在windows下又报这个错：

```shell
[vite] Internal server error: Preprocessor dependency "less" not found. Did you install it?

```

**Comment by transtone** [comment]
https://github.com/GitOfZGT/vite-plugin-theme-preprocessor/issues/16
